import { installCustomSiteTheme } from "./theme";
import { installPlayDocumentLoader } from "./playDocumentLoader";
import { installUpdateNotifier } from "./updateNotifier";
import { installPlayInBrowserButton } from "./playInBrowserButton";
import { installUgcLabs } from "../ugc/UgcLabs";
import { installHomeDiscovery } from "../site/HomeDiscoveryService";
import { installSiteChrome } from "../site/SiteChromeService";
import { installSiteSearch } from "../site/SiteSearchService";
import { installHomeFriendRail } from "../site/HomeFriendRailService";
import "../cosmetics/VortexWebCosmetics.js";
import "../cosmetics/ProfileCosmetics.js";

installCustomSiteTheme();
installPlayDocumentLoader();
installUpdateNotifier();
installPlayInBrowserButton();
installUgcLabs();
installSiteChrome();
installSiteSearch();
installHomeDiscovery();
installHomeFriendRail();
